### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by WeSrc-Yin** [zlgopen/awtk-widget-code-edit#1]
demos/app_main.c:5:29: fatal error: ../res/assets.inc: No such file or directory
compilation terminated.
scons: *** [demos/app_main.o] Error 1
scons: building terminated because of errors.

**Comment by xianjimli** [comment]
python scripts/update_res.py all

**Comment by WeSrc-Yin** [comment]
-Isrc/scintilla/awtk src/code_edit/code_edit.cpp
src/code_edit/code_edit.cpp:38:23: fatal error: string_view: No such file or directory
compilation terminated.

**Comment by xianjimli** [comment]
要用支持c++17才行
